name: Build investigate

on:
#  push: # Any branch
  workflow_dispatch:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build ZeroTier package for pfSense
#    env:
#      MYTOKEN : ${{ secrets.MYTOKEN }}
#      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Do the build
      id: create_release
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          source ~/.profile
          pkg install -y git gmake tree

        run: |
          
          # pwd 
          #  /home/runner/work/pfSense-pkg-zerotier/pfSense-pkg-zerotier
          git clone https://github.com/pfsense/FreeBSD-ports.git
          echo 'ALLOW_UNSUPPORTED_SYSTEM=YES' | sudo tee -a /etc/make.conf
          # Avoid copy of FreeBSD-ports into itself
          rsync -av --exclude='FreeBSD-ports' . FreeBSD-ports/net/pfSense-pkg-zerotier
          cd FreeBSD-ports/net/pfSense-pkg-zerotier
          echo "Vitali: make clean"
          find . -name info.xml
          make clean > make_clean.log 2>&1
          echo "Vitali: make package"
          find . -name info.xml
          make package > make_package.log 2>&1
          echo "Vitali: Done"
          find . -name info.xml
          ls -la
          echo "Vitali: tree"
          tree .

    - name: Upload make clean log
      uses: actions/upload-artifact@v3
      with:
        name: make-clean-log
        path: FreeBSD-ports/net/pfSense-pkg-zerotier/make_clean.log

    - name: Upload make package log
      uses: actions/upload-artifact@v3
      with:
        name: make-package-log
        path: FreeBSD-ports/net/pfSense-pkg-zerotier/make_package.log