name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
#    env:
#      MYTOKEN : ${{ secrets.MYTOKEN }}
#      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
#        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          source ~/.profile
          pkg install -y git gmake

        run: |
          git clone https://github.com/pfsense/FreeBSD-ports.git
          echo 'ALLOW_UNSUPPORTED_SYSTEM=YES' | sudo tee -a /etc/make.conf
          cp -r . FreeBSD-ports/net/pfSense-pkg-zerotier
          cd FreeBSD-ports/net/pfSense-pkg-zerotier
          make clean
          make package
          cp work/pkg/pfSense-pkg-zerotier-0.00.1.txz .